# Generated by Django 6.1 on 2026-08-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
