# Generated by Django 6.1 on 2026-08-27 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_proveedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='productos.proveedor'),
            preserve_default=False,
        ),
    ]
